# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate new migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path pathplist to be prepended to sys.path and in what order
# should be a list of paths separated by colons or semicolons
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to use for "slug" in filename
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported from
# sys.path when running the command
# import_sys_path = false

version_path_separator = os  # Use os.pathsep. Default configuration used for new projects.

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
