"""add_notes_indexes

Revision ID: 18f1d38d638b
Revises: e4ffe7e8e71b
Create Date: 2026-07-05 20:16:50.057380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f1d38d638b'
down_revision: Union[str, None] = 'e4ffe7e8e71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notes_resources_file_name'), 'notes_resources', ['file_name'], unique=False)
    op.create_index(op.f('ix_notes_resources_resource_name'), 'notes_resources', ['resource_name'], unique=False)
    op.create_index(op.f('ix_notes_resources_section_id'), 'notes_resources', ['section_id'], unique=False)
    op.create_index(op.f('ix_notes_sections_notes_subject_id'), 'notes_sections', ['notes_subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_sections_notes_subject_id'), table_name='notes_sections')
    op.drop_index(op.f('ix_notes_resources_section_id'), table_name='notes_resources')
    op.drop_index(op.f('ix_notes_resources_resource_name'), table_name='notes_resources')
    op.drop_index(op.f('ix_notes_resources_file_name'), table_name='notes_resources')
    # ### end Alembic commands ###
