"""create_semester_and_attendance_settings_tables

Revision ID: 192b4793464e
Revises: None
Create Date: 2026-07-03 12:04:49.452210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192b4793464e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('semester_number > 0', name='semester_number_positive'),
    sa.PrimaryKeyConstraint('semester_id'),
    sa.UniqueConstraint('semester_number')
    )
    op.create_index(op.f('ix_semesters_semester_id'), 'semesters', ['semester_id'], unique=False)
    op.create_table('attendance_settings',
    sa.Column('attendance_settings_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('criteria_mode', sa.Enum('OVERALL', 'SUBJECT', 'CUSTOM', name='criteria_mode'), nullable=False),
    sa.Column('overall_attendance_goal', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('overall_attendance_goal IS NULL OR (overall_attendance_goal >= 1 AND overall_attendance_goal <= 100)', name='attendance_goal_range'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_settings_id'),
    sa.UniqueConstraint('semester_id')
    )
    op.create_index(op.f('ix_attendance_settings_attendance_settings_id'), 'attendance_settings', ['attendance_settings_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_settings_attendance_settings_id'), table_name='attendance_settings')
    op.drop_table('attendance_settings')
    op.drop_index(op.f('ix_semesters_semester_id'), table_name='semesters')
    op.drop_table('semesters')
    # ### end Alembic commands ###
