"""create_subjects_and_notes_subjects_tables

Revision ID: 1a9ff58b8423
Revises: 192b4793464e
Create Date: 2026-07-03 12:38:19.096480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9ff58b8423'
down_revision: Union[str, None] = '192b4793464e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_subjects',
    sa.Column('notes_subject_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('notes_subject_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notes_subject_id'),
    sa.UniqueConstraint('semester_id', 'notes_subject_name', name='uq_notes_subject_per_semester')
    )
    op.create_index(op.f('ix_notes_subjects_notes_subject_id'), 'notes_subjects', ['notes_subject_id'], unique=False)
    op.create_table('subjects',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('faculty_name', sa.String(length=100), nullable=True),
    sa.Column('theme_color', sa.String(length=7), nullable=True),
    sa.Column('attendance_goal', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attendance_goal >= 1 AND attendance_goal <= 100', name='attendance_goal_range_subjects'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('semester_id', 'subject_name', name='uq_subject_per_semester')
    )
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_notes_subjects_notes_subject_id'), table_name='notes_subjects')
    op.drop_table('notes_subjects')
    # ### end Alembic commands ###
