"""create_lecture_template_instance_holiday_tables

Revision ID: 2db1602c28b4
Revises: 1a9ff58b8423
Create Date: 2026-07-03 13:14:47.354877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db1602c28b4'
down_revision: Union[str, None] = '1a9ff58b8423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('holiday_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('holiday_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.semester_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('holiday_id'),
    sa.UniqueConstraint('semester_id', 'holiday_date', name='uq_holiday_per_semester')
    )
    op.create_index(op.f('ix_holidays_holiday_id'), 'holidays', ['holiday_id'], unique=False)
    op.create_table('lecture_templates',
    sa.Column('lecture_template_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('day_of_week >= 1 AND day_of_week <= 7', name='day_of_week_range'),
    sa.CheckConstraint('start_time < end_time', name='start_time_before_end_time'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lecture_template_id'),
    sa.UniqueConstraint('subject_id', 'day_of_week', 'start_time', name='uq_lecture_template_schedule')
    )
    op.create_index(op.f('ix_lecture_templates_lecture_template_id'), 'lecture_templates', ['lecture_template_id'], unique=False)
    op.create_table('lecture_instances',
    sa.Column('lecture_instance_id', sa.Uuid(), nullable=False),
    sa.Column('lecture_template_id', sa.Uuid(), nullable=False),
    sa.Column('lecture_date', sa.Date(), nullable=False),
    sa.Column('lecture_status', sa.Enum('SCHEDULED', 'HOLIDAY', 'CANCELLED', name='lecture_status'), nullable=False),
    sa.Column('attendance_status', sa.Enum('UNMARKED', 'PRESENT', 'ABSENT', name='attendance_status'), nullable=False),
    sa.Column('marked_by', sa.Enum('USER', 'BOT', 'REVIEW_QUEUE', name='marked_by'), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lecture_template_id'], ['lecture_templates.lecture_template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lecture_instance_id')
    )
    op.create_index(op.f('ix_lecture_instances_lecture_instance_id'), 'lecture_instances', ['lecture_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lecture_instances_lecture_instance_id'), table_name='lecture_instances')
    op.drop_table('lecture_instances')
    op.drop_index(op.f('ix_lecture_templates_lecture_template_id'), table_name='lecture_templates')
    op.drop_table('lecture_templates')
    op.drop_index(op.f('ix_holidays_holiday_id'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
