"""create_users_and_ownership

Revision ID: 317f52aca7c2
Revises: 567b7ac1f0ec
Create Date: 2026-07-10 13:42:12.450402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317f52aca7c2'
down_revision: Union[str, None] = '567b7ac1f0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_semesters_user_id_semester_number'), 'semesters', type_='unique')
    op.create_unique_constraint('uq_semester_per_user', 'semesters', ['user_id', 'semester_number'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_semester_per_user', 'semesters', type_='unique')
    op.create_unique_constraint(op.f('uq_semesters_user_id_semester_number'), 'semesters', ['user_id', 'semester_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
