"""create_activity_logs

Revision ID: 50e34ed09b6c
Revises: 6e78de13a647
Create Date: 2026-07-05 23:27:54.841626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e34ed09b6c'
down_revision: Union[str, None] = '6e78de13a647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'BOT', 'REVIEW_QUEUE', 'SYSTEM', name='activity_actor_type'), nullable=False),
    sa.Column('entity_type', sa.Enum('SEMESTER', 'SUBJECT', 'ATTENDANCE', 'HOLIDAY', 'TODO', 'NOTES', 'REVIEW_QUEUE', 'FINANCE', 'SETTINGS', name='activity_entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'COMPLETED', 'RESOLVED', 'DOWNLOADED', 'UPLOADED', 'MARKED_PRESENT', 'MARKED_ABSENT', 'MARKED_HOLIDAY', name='activity_action_type'), nullable=False),
    sa.Column('activity_message', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activity_logs_action_type'), 'activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_activity_id'), 'activity_logs', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_type'), 'activity_logs', ['actor_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_correlation_id'), 'activity_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_correlation_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
