"""create_review_queue

Revision ID: 559c3919a539
Revises: 18f1d38d638b
Create Date: 2026-07-05 20:22:33.446693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559c3919a539'
down_revision: Union[str, None] = '18f1d38d638b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_queue',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('review_type', sa.Enum('MISSING_INFORMATION', 'CONFIRMATION_REQUIRED', 'MANUAL_REVIEW', name='review_type'), nullable=False),
    sa.Column('entity_type', sa.Enum('ATTENDANCE', 'TODO', 'FINANCE', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('review_message', sa.Text(), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'RESOLVED', name='review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_review_queue_entity_id'), 'review_queue', ['entity_id'], unique=False)
    op.create_index(op.f('ix_review_queue_review_id'), 'review_queue', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_queue_review_status'), 'review_queue', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_queue_review_status'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_review_id'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_entity_id'), table_name='review_queue')
    op.drop_table('review_queue')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS review_type CASCADE")
    op.execute("DROP TYPE IF EXISTS entity_type CASCADE")
    op.execute("DROP TYPE IF EXISTS review_status CASCADE")

