"""remediate_database_audit_02

Revision ID: 5c85b9ed5223
Revises: 9a79ee8c5960
Create Date: 2026-07-09 19:33:53.900149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c85b9ed5223'
down_revision: Union[str, None] = '9a79ee8c5960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_holidays_semester_id_holiday_date', 'holidays', ['semester_id', 'holiday_date'], unique=False)
    op.create_unique_constraint('uq_lecture_instance_template_date', 'lecture_instances', ['lecture_template_id', 'lecture_date'])
    op.create_index(op.f('ix_todos_due_datetime'), 'todos', ['due_datetime'], unique=False)
    op.create_index(op.f('ix_todos_status'), 'todos', ['status'], unique=False)
    op.create_check_constraint('semester_date_order', 'semesters', 'start_date < end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('semester_date_order', 'semesters', type_='check')
    op.drop_index(op.f('ix_todos_status'), table_name='todos')
    op.drop_index(op.f('ix_todos_due_datetime'), table_name='todos')
    op.drop_constraint('uq_lecture_instance_template_date', 'lecture_instances', type_='unique')
    op.drop_index('ix_holidays_semester_id_holiday_date', table_name='holidays')
    # ### end Alembic commands ###
