"""create_todos_table

Revision ID: 6e718cd5065a
Revises: ca2a9e095c10
Create Date: 2026-07-05 18:13:13.637573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e718cd5065a'
down_revision: Union[str, None] = 'ca2a9e095c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('todo_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('ACADEMIC', 'PERSONAL', 'WORK', 'HEALTH', 'OTHER', name='todo_category'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='todo_priority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='todo_status'), nullable=False),
    sa.Column('created_by', sa.Enum('USER', 'BOT', 'REVIEW_QUEUE', name='todo_created_by'), nullable=False),
    sa.Column('due_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('todo_id')
    )
    op.create_index(op.f('ix_todos_todo_id'), 'todos', ['todo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_todo_id'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS todo_category CASCADE")
    op.execute("DROP TYPE IF EXISTS todo_priority CASCADE")
    op.execute("DROP TYPE IF EXISTS todo_status CASCADE")
    op.execute("DROP TYPE IF EXISTS todo_created_by CASCADE")
