"""refine_review_queue

Revision ID: 6e78de13a647
Revises: 559c3919a539
Create Date: 2026-07-05 20:29:34.866131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e78de13a647'
down_revision: Union[str, None] = '559c3919a539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE resolved_by AS ENUM ('USER', 'SYSTEM', 'ADMIN')")
    op.add_column(
        'review_queue',
        sa.Column(
            'resolved_by',
            sa.Enum('USER', 'SYSTEM', 'ADMIN', name='resolved_by', create_type=False),
            nullable=False,
            server_default='USER'
        )
    )
    op.create_index(op.f('ix_review_queue_created_at'), 'review_queue', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_queue_created_at'), table_name='review_queue')
    op.drop_column('review_queue', 'resolved_by')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS resolved_by CASCADE")
