"""add_lecture_date_index

Revision ID: 905f6a12361e
Revises: 5c85b9ed5223
Create Date: 2026-07-09 20:30:45.674673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905f6a12361e'
down_revision: Union[str, None] = '5c85b9ed5223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lecture_instances_lecture_date'), 'lecture_instances', ['lecture_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lecture_instances_lecture_date'), table_name='lecture_instances')
    # ### end Alembic commands ###
