"""remove_todo_category

Revision ID: 9a79ee8c5960
Revises: 50e34ed09b6c
Create Date: 2026-07-07 18:47:10.295640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a79ee8c5960'
down_revision: Union[str, None] = '50e34ed09b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'category')
    op.execute("DROP TYPE todo_category")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE todo_category AS ENUM ('ACADEMIC', 'PERSONAL', 'WORK', 'HEALTH', 'OTHER')")
    op.add_column('todos', sa.Column('category', postgresql.ENUM('ACADEMIC', 'PERSONAL', 'WORK', 'HEALTH', 'OTHER', name='todo_category'), server_default='OTHER', nullable=False))
    # ### end Alembic commands ###
