"""create_app_settings_table

Revision ID: ca2a9e095c10
Revises: 2db1602c28b4
Create Date: 2026-07-05 17:56:55.335440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2a9e095c10'
down_revision: Union[str, None] = '2db1602c28b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('settings_id', sa.SmallInteger(), nullable=False),
    sa.Column('active_semester_id', sa.Uuid(), nullable=True),
    sa.Column('theme_mode', sa.Enum('LIGHT', 'DARK', 'SYSTEM', name='theme_mode'), nullable=False),
    sa.Column('finance_enabled', sa.Boolean(), nullable=False),
    sa.Column('morning_digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('night_digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('attendance_prompt_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes_download_directory', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('settings_id = 1', name='app_settings_single_row'),
    sa.ForeignKeyConstraint(['active_semester_id'], ['semesters.semester_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('settings_id')
    )
    # ### end Alembic commands ###

    # Seed default singleton row
    op.execute(
        "INSERT INTO app_settings (settings_id, theme_mode, finance_enabled, morning_digest_enabled, night_digest_enabled, attendance_prompt_enabled, created_at, updated_at) "
        "VALUES (1, 'SYSTEM', false, true, true, true, NOW(), NOW())"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS theme_mode CASCADE")


