"""create_notes_tables

Revision ID: e4ffe7e8e71b
Revises: 6e718cd5065a
Create Date: 2026-07-05 19:31:47.526263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ffe7e8e71b'
down_revision: Union[str, None] = '6e718cd5065a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_sections',
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('notes_subject_id', sa.Uuid(), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notes_subject_id'], ['notes_subjects.notes_subject_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id'),
    sa.UniqueConstraint('notes_subject_id', 'section_name', name='uq_notes_section_per_subject')
    )
    op.create_index(op.f('ix_notes_sections_section_id'), 'notes_sections', ['section_id'], unique=False)
    op.create_table('notes_resources',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('uploaded_via', sa.Enum('APP', 'WHATSAPP', 'OCR', 'REVIEW_QUEUE', 'API', name='uploaded_via'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['notes_sections.section_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id'),
    sa.UniqueConstraint('section_id', 'file_name', name='uq_notes_resource_per_section')
    )
    op.create_index(op.f('ix_notes_resources_resource_id'), 'notes_resources', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_resources_resource_id'), table_name='notes_resources')
    op.drop_table('notes_resources')
    op.drop_index(op.f('ix_notes_sections_section_id'), table_name='notes_sections')
    op.drop_table('notes_sections')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS uploaded_via CASCADE")
